### ISSUE TITLE
NameError: global name 'PermissionError' is not defined

### ISSUE THREAD

**Issue by amstan** [amstan/hyperserv#21]
<pre>
ERROR:root:Uncaught exception occured in event handler.
ERROR:root:Traceback (most recent call last):
  File "/storage/raided/opt/sauer/hyperserv/src/pyscripts/hyperserv/events.py", line 23, in trigger
    event(*args)
  File "/storage/raided/opt/sauer/hyperserv/src/pyscripts/hyperserv/clientcommands.py", line 17, in clientSetMaster
    simpleMasterRequest(caller)
  File "/storage/raided/opt/sauer/hyperserv/src/pyscripts/hyperserv/clientcommands.py", line 68, in simpleMasterRequest
    raise PermissionError("There are masters/admins present.")
NameError: global name 'PermissionError' is not defined
</pre>

**Comment by amstan** [comment]
fixed in 53ba2b7f1c3f56ad50a45ca58b30b0093ad8ce18
