### ISSUE TITLE
New error with starting server D:

### ISSUE THREAD

**Issue by fetzjr** [amstan/hyperserv#43]
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
unknown command: cfg
Configuration loaded.
HyperShade initialized.
Traceback (most recent call last):
  File "/home/hyper/hyperserv/src/pyscripts/hyperserv/plugins.py", line 8, in <module>
    import hyperserv.ingame
  File "/home/hyper/hyperserv/src/pyscripts/hyperserv/ingame.py", line 28, in <module>
    systemCS.executestring("map %s %s" % (config["defaultmap"],config["defaultmode"]))
  File "/home/hyper/hyperserv/src/pyscripts/lib/cubescript.py", line 145, in functionErrorWrapper
    return functionpointer(self,_params)
  File "/home/hyper/hyperserv/src/pyscripts/hypershade/cubescript.py", line 35, in <lambda>
    functionpointer=lambda *args: self.wrapper(f,_args)
  File "/home/hyper/hyperserv/src/pyscripts/hypershade/cubescript.py", line 28, in wrapper
    return f(owner,*args[1:])
  File "/home/hyper/hyperserv/src/pyscripts/hyperserv/servercommands.py", line 32, in changeMap
    mode=modeNumber(mode)
  File "/home/hyper/hyperserv/src/pyscripts/hypershade/util.py", line 80, in modeNumber
    raise ValueError('Invalid mode')
ValueError: Invalid mode
Error initializing python modules.
Server initialization failed.

**Comment by fetzjr** [comment]
Can you ATLEAST tell me how to fix it?
